---
abstract: 'This distribution is for communicating with a MOBY Central registry'
author:
  - 'Mark Wilkinson <markw@illuminae.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Pod: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MOBY-Client
no_index:
  directory:
    - inc
    - share
    - t
requires:
  CGI: 0
  HTML::Entities: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  RDF::Core: 0.51
  SOAP::Lite: 0.6
  URI::Escape: 0
  WSRF::Lite: 0.8.2.5
  XML::LibXML: 0
  XML::LibXML::Common: 0.13
  XML::SemanticCompare: 0.91
  XML::Simple: 2.18
resources:
  license: http://dev.perl.org/licenses/
version: 1.05
