--- 
author: 
  - Mark Wilkinson <markw@illuminae.com>
build_requires: 
  Test::More: 0
  Test::Pod: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MOBY-Client
no_index: 
  directory: 
    - inc
    - t
requires: 
  CGI: 0
  HTML::Entities: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  SOAP::Lite: 0.60
  URI::Escape: 0
  XML::LibXML: 0
version: 1.0
